export const LOG_OUT = 'LOG_OUT';
export const LOG_IN = 'LOG_IN';
export const FETCH_FACILITY_REQUEST = 'FETCH_FACILITY_REQUEST';
export const FETCH_FACILITY_SUCCESS = 'FETCH_FACILITY_SUCCESS';
export const FETCH_FACILITY_FAILURE = 'FETCH_FACILITY_FAILURE';
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
